# Generated by Django 5.1.1 on 2024-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialization',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
